// Theme System for InstallmentGuard
export const themes = {
  light: {
    name: 'light',
    colors: {
      background: '#ffffff',
      foreground: '#0f172a',
      card: '#ffffff',
      cardForeground: '#0f172a',
      popover: '#ffffff',
      popoverForeground: '#0f172a',
      primary: '#009933',
      primaryForeground: '#ffffff',
      secondary: '#f1f5f9',
      secondaryForeground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      accent: '#f1f5f9',
      accentForeground: '#0f172a',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#009933',
    },
  },
  dark: {
    name: 'dark',
    colors: {
      background: '#0f172a',
      foreground: '#f8fafc',
      card: '#1e293b',
      cardForeground: '#f8fafc',
      popover: '#1e293b',
      popoverForeground: '#f8fafc',
      primary: '#009933',
      primaryForeground: '#ffffff',
      secondary: '#334155',
      secondaryForeground: '#f8fafc',
      muted: '#334155',
      mutedForeground: '#94a3b8',
      accent: '#334155',
      accentForeground: '#f8fafc',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#334155',
      input: '#334155',
      ring: '#009933',
    },
  },
} as const;

export type Theme = typeof themes.light;
export type ThemeName = keyof typeof themes;

// CSS Variables for theme switching
export const getCSSVariables = (theme: Theme) => ({
  '--background': theme.colors.background,
  '--foreground': theme.colors.foreground,
  '--card': theme.colors.card,
  '--card-foreground': theme.colors.cardForeground,
  '--popover': theme.colors.popover,
  '--popover-foreground': theme.colors.popoverForeground,
  '--primary': theme.colors.primary,
  '--primary-foreground': theme.colors.primaryForeground,
  '--secondary': theme.colors.secondary,
  '--secondary-foreground': theme.colors.secondaryForeground,
  '--muted': theme.colors.muted,
  '--muted-foreground': theme.colors.mutedForeground,
  '--accent': theme.colors.accent,
  '--accent-foreground': theme.colors.accentForeground,
  '--destructive': theme.colors.destructive,
  '--destructive-foreground': theme.colors.destructiveForeground,
  '--border': theme.colors.border,
  '--input': theme.colors.input,
  '--ring': theme.colors.ring,
});